### ISSUE TITLE
Glitch when running validation

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/my-ruby-deployer#7]
```ruby
# setup deploying rutines
BlackStack::Deployer::add_routine({
  :name => 'install-cockroach-cluster',
})
```

Output:

```bash
C:/code2/blackstack-deployer/lib/blackstack-deployer.rb:99:in `descriptor_errors': undefined method `size' for nil:NilClass (NoMethodError)

        errors << "The parameter h[:commands] does not have at least one element" unless h[:commands].size > 0\r
                                                                                                     ^^^^^
        from C:/code2/blackstack-deployer/lib/blackstack-deployer.rb:467:in `add_routine'
        from 1.rb:251:in `<main>'
```

**Comment by leandrosardi** [comment]
CANCELED
